#include "images.h"

const ext_img_desc_t images[39] = {
    { "0_1_button", &img_0_1_button },
    { "0_01_button", &img_0_01_button },
    { "1_button", &img_1_button },
    { "10_button", &img_10_button },
    { "arrow_Xright_button", &img_arrow_xright_button },
    { "arrow_Ydown_button", &img_arrow_ydown_button },
    { "arrow_Yup_button", &img_arrow_yup_button },
    { "arrow_Zdown_button", &img_arrow_zdown_button },
    { "arrow_Zup_button", &img_arrow_zup_button },
    { "auto_button", &img_auto_button },
    { "back_button", &img_back_button },
    { "cancel_button", &img_cancel_button },
    { "cmd_button", &img_cmd_button },
    { "delete_button", &img_delete_button },
    { "home_button", &img_home_button },
    { "info_button", &img_info_button },
    { "mill_button", &img_mill_button },
    { "more_button", &img_more_button },
    { "move_button", &img_move_button },
    { "next_button", &img_next_button },
    { "pause_button", &img_pause_button },
    { "previous_button", &img_previous_button },
    { "reset_button", &img_reset_button },
    { "resume_button", &img_resume_button },
    { "sdcard_button", &img_sdcard_button },
    { "see_gcode_button", &img_see_gcode_button },
    { "set_WCS_button", &img_set_wcs_button },
    { "setup_button", &img_setup_button },
    { "setX_button", &img_set_x_button },
    { "setXYZ_button", &img_set_xyz_button },
    { "setY_button", &img_set_y_button },
    { "setZ_button", &img_set_z_button },
    { "stop_PC_button", &img_stop_pc_button },
    { "telnet_button", &img_telnet_button },
    { "tool_button", &img_tool_button },
    { "unlock_button", &img_unlock_button },
    { "up_button", &img_up_button },
    { "usb_button", &img_usb_button },
    { "arrow_Xleft_button", &img_arrow_xleft_button },
};
